system:
  geometry:
    deformation_scale: 1.5
  prompt_processor:
    prompt: "A bald eagle is flying"
  geometry_convert_from: "../dream-in-4D-output/magic123-coarse-if-new/eagle.png-A_bald_eagle_is_flying@20231207-123149/ckpts/last.ckpt"